openapi: 3.0.1
info:
  title: Jira Slack integration
  description: Small application that notify slack when an issue is added to the sprint
  version: 1.0.0
servers:
  - url: /api/v1
tags:
  - name: Webhook
    description: Endpoint that receive a webhook from Jira
  - name: Specification
    description: The swagger API specification
paths:
  /webhook:
    post:
      tags:
        - Webhook
      description: Create a new example
      requestBody:
        description: an example
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/JiraIssue'
        required: true
      responses:
        200:
          description: Message sent to slack
          content: {}
        400:
          description: Error happend when trying to parse issue
          content: {}
  /spec:
    get:
      tags:
        - Specification
      responses:
        200:
          description: Return the API specification
          content: {}
components:
  schemas:
    JiraIssue:
      title: jiraissue
      required:
        - user
        - issue
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        issue:
          $ref: '#/components/schemas/Issue'
        changelog:
          $ref: '#/components/schemas/Changelog'
    User:
      title: user
      required:
        - displayName
        - emailAddress
      type: object
      properties:
        displayName:
          type: string
          example: Rick Sanchez
        emailAddress:
          type: string
          format: email
          example: rick@sanchez.com
    Issue:
      title: issue
      required:
        - key
        - fields
      type: object
      properties:
        key:
          type: string
          example: C-137
        fields:
          type: object
    Changelog:
      title: Changelog
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
                example: Sprint
              fieldtype:
                type: string
                example: Custom
              from:
                type: string
              fromString:
                type: string
              to:
                type: string
                example: "123"
              toString:
                type: string
                example: "SP1"
